### ISSUE TITLE
Cannot find SourceMap 'index.js.map'

### ISSUE THREAD

**Issue by gryole** [ShieldBattery/node-interval-tree#3]
Published `index.js` contains `//# sourceMappingURL=index.js.map`, but there is no source map included.
Package `"version": "1.1.4"`

Could you, please, add source maps to published files - `"files"` property at `package.json`
or
set `"sourceMap": false` at `tsconfig.json`

**Comment by 2Pacalypse-** [comment]
Oops, missed that one. Thanks for reporting it!

Published the new version with the source maps included (hopefully).

**Comment by AramLokyan** [comment]
Now I have warning
C:/Projects/myProject/~/node-interval-tree/lib/index.js
(Emitted value instead of an instance of Error) Cannot find source file '../index.ts': Error: Can't resolve '../index.ts' in 'C:\Projects\myProject\node_modules\node-interval-tree\lib'

It looks like sourceMaps reference to not existing source file "sources":["../index.ts"].

**Comment by 2Pacalypse-** [comment]
Weird. I thought original source file was not necessary to publish, but I guess I don't understand source maps properly :d

Anyway, published the new version with the original source file included as well.
