### ISSUE TITLE
Es6 taget

### ISSUE THREAD

**Issue by gryole** [ShieldBattery/node-interval-tree#4]
Is there any special case for using ` "target": "es6",` at `tsconfig.json` ?

Because `lib/index.js` is shipped with ES6 and could not be used as is and should be recompiled to ES5.

**Comment by 2Pacalypse-** [comment]
It's because `es5` target in typescript's compiler didn't support iterators.

However, after doing some research, I see they actually have support for iterators in lower targets of ES, behind a flag: https://github.com/Microsoft/TypeScript/pull/12346

I just published a new version with a `es5` target, and hopefully everything works :d. I have very little experience with Typescript, so please report any issues if you encounter them.

Also, `core-js` typings shouldn't be necessary anymore, so you can uninstall those if you installed them specifically for this project.
